@startuml

skinparam monochrome true
hide footbox

participant "Test" as actor
participant "juego:Juego" as Juego
participant "pregunta:Pregunta" as Pregunta
participant "jugador:Jugador" as Jugador
participant "multiplicador:MultiplicadorX3" as MultiplicadorX3




create Juego
actor->Juego: Juego()



create Jugador
actor->Jugador: Jugador("Juan")

create MultiplicadorX3
actor->MultiplicadorX3: MultiplicadorX3()

actor->Juego: agregarJugador(jugador)
activate Juego

actor->Juego: setearPregunta()

actor->Juego: obtenerPregunta()
create Pregunta 
Juego->Pregunta: create


actor<--Juego: pregunta
actor->Juego: getJugadorActual()
actor<--Juego: jugador
actor->Pregunta: agregarOpcion(pregunta, 2)
activate Pregunta
actor->Pregunta: agregarOpcion(pregunta, 5)
deactivate Pregunta
actor->Juego: verificarRespuestaJugador(jugador, pregunta)
Juego->Pregunta: verificarRespuesta(jugador.getRespuesta())
activate Pregunta
Pregunta-->Juego: Puntaje(1)
deactivate Pregunta
Juego->Juego: agregarPuntaje(jugador, Puntaje(1))
actor->Jugador: usarMultiplicador(pregunta, multiplicador)
activate Jugador
Jugador->Pregunta: setMultiplicador(multiplicador)
activate Pregunta
Juego->Pregunta: verificarRespuesta(jugador.getRespuesta())
Pregunta-->Pregunta: Puntaje(2)
Pregunta->MultiplicadorX3: multiplicar(Puntaje(2))
activate MultiplicadorX3
MultiplicadorX3-->Pregunta: Puntaje(6)
deactivate MultiplicadorX3
Pregunta-->Juego: Puntaje(6)
deactivate Pregunta
Juego->Juego: agregarPuntaje(jugador, Puntaje(6))

actor->Juego: resetearRespuestaJugadores()
actor->Juego: asignarPuntajeJugadores()
Juego->Jugador: asignarPuntos(Puntaje(6)) 
