@startuml

skinparam monochrome true
hide footbox

participant "Test" as actor
participant "opcion1:Opcion" as opcion1
participant "opcion2:Opcion" as opcion2
participant "opcion3:Opcion" as opcion3
participant "respuestaCorrecta:Respuesta" as respuestaCorrecta
participant "respuestaJugador:Respuesta" as respuestaJugador
participant "tipo:MultipleChoice" as tipo
participant "pregunta:PreguntaConPenalidad" as pregunta
participant "puntaje:Puntaje" as puntaje

create opcion1
actor -> opcion1: Opcion("Uno")
create opcion2
actor -> opcion2: Opcion("Dos")
create opcion3
actor -> opcion3: Opcion("Tres")
create respuestaCorrecta
actor -> respuestaCorrecta: Respuesta()
actor -> respuestaCorrecta: agregarOpcion(opcion1)
activate respuestaCorrecta
actor -> respuestaCorrecta: agregarOpcion(opcion2)
deactivate respuestaCorrecta
create respuestaJugador
actor -> respuestaJugador: Respuesta()
actor -> respuestaJugador: agregarOpcion(opcion1)
activate respuestaJugador
actor -> respuestaJugador: agregarOpcion(opcion2)
deactivate respuestaJugador
create tipo
actor -> tipo: MultipleChoice()
create pregunta
actor -> pregunta: PreguntaConPenalidad(tipo, respuestaCorrecta)
actor -> pregunta: verificarRespuesta(respuestaJugador)
activate pregunta
pregunta -> tipo: respondidoCorrectamente(respuestaCorrecta, respuestaJugador)
activate tipo
tipo -> respuestaCorrecta: corregirRespuestaSinImportarElOrden(respuestaJugador)
activate respuestaCorrecta
respuestaCorrecta --> tipo: true
deactivate respuestaCorrecta
tipo --> pregunta: true
deactivate tipo
create puntaje
pregunta -> puntaje: Puntaje(2)
pregunta --> actor: puntaje
deactivate pregunta

@enduml