@startuml

skinparam monochrome true
hide circle
skinparam classAttributeIconSize 0

abstract class Pregunta {
    - tipo:Tipo
    - tema:String
    - tipoPregunta:String
    - enunciado:String
    - textoRespuesta:String
    - respuestaCorrecta:Respuesta
    - numeroOpcion:int
    + Pregunta(tipo:Tipo, respuestaCorrecta:Respuesta)
    + Pregunta(tipo:Tipo, respuestaCorrecta:Respuesta, enunciado:String, tipoPregunta:String, opciones:ArrayList<Opcion>, tema:String, textoRespuesta:String)
    + setMultiplicador(Multiplicador multiplicador)
    + mostrarOpcion():Opcion
    + setearRespuestaJugador(respuestaJugador:Respuesta, numeroOpcion:int)
    + getEnunciado():String
    + getTema():String
    + getTipoPregunta():String
    + getTextoRespuesta():String
    + getRespuestaCorrecta():Respuesta
    + tienePenalidad():boolean
    + verificarRespuesta(respuestaJugador:Respuesta):Puntaje
}

class PreguntaConPenalidad extends Pregunta{
    + tienePenalidad():boolean
    + verificarRespuesta(Respuesta respuestaJugador):Puntaje
}

class PreguntaParcial extends Pregunta{
    + tienePenalidad():boolean
    + verificarRespuesta(Respuesta respuestaJugador):Puntaje
}

class PreguntaSimple extends Pregunta {
    + tienePenalidad():boolean
    + verificarRespuesta(Respuesta respuestaJugador):Puntaje
}

@enduml